name: second_github_action
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: xxx
          aws-secret-access-key: xxx
          aws-region: us-east-1
      - name: List files (for debugging)
        run: ls -al
      - name: Upload to s3
        run: aws s3 cp hello.txt s3://githubactionsdemo-amp
